repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 38b88246ccc552bffaaf54259d064beeee434539  # frozen: v4.0.1
  hooks:
  - id: check-yaml
  - id: check-toml
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: 6f51a66bba59954917140ec2eeeaa4d5e630e6ce  # frozen: v1.9.0
  hooks:
  - id: python-use-type-annotations
  - id: python-check-blanket-noqa
- repo: https://github.com/PyCQA/isort
  rev: fd5ba70665a37ec301a1f714ed09336048b3be63  # frozen: 5.9.3
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: 64c8be01f0cfedc94cb1c9ebd342ea77cafbb78a  # frozen: 21.10b0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/flake8
  rev: cbeb4c9c4137cff1568659fcc48e8b85cddd0c8d  # frozen: 4.0.1
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-comprehensions
- repo: https://github.com/myint/docformatter
  rev: 67919ee01837761f2d954d7fbb08c12cdd38ec5a  # frozen: v1.4
  hooks:
  - id: docformatter
- repo: https://github.com/executablebooks/mdformat
  rev: 427df9181bd4d8e65c1108b912ad47a81628f03b  # frozen: 0.7.10
  hooks:
  - id: mdformat
    files: 'README.md'
